
f = open('D:\\record.txt',encoding='utf-8')
print(f.read())
print(f.read())
f.close()
f = open('D:\\record.txt',encoding='utf-8')
print(88)
print(f.read(20))
print(f.tell())
print(f.seek(0,0))
print(f.tell())
print(333)
print(f.readline(50))
f.seek(0,0)
print(444)
for esch in f:
    print(esch)
f.close()
f = open('D:\\ccc.txt','w',encoding='utf-8')
f.write('我爱曹碧')
f.close()